# Generated by Django 3.2.7 on 2026-03-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_masuk', models.PositiveSmallIntegerField()),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angkatan_set', to='api.programstudi')),
            ],
            options={
                'ordering': ['-tahun_masuk'],
            },
        ),
        migrations.CreateModel(
            name='AturanJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='default', max_length=50, unique=True)),
                ('jam_mulai', models.TimeField(default='08:00')),
                ('jam_selesai', models.TimeField(default='18:00')),
                ('menit_per_sks', models.PositiveSmallIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('kapasitas', models.PositiveIntegerField(default=30)),
                ('tipe', models.CharField(choices=[('KELAS', 'Kelas'), ('LAB', 'Laboratorium')], default='TEORI', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Pembelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_kelas', models.PositiveSmallIntegerField(default=1)),
                ('aktif', models.BooleanField(default=True)),
                ('angkatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.angkatan')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dosen')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matakuliah')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programstudi')),
            ],
            options={
                'ordering': ['prodi__kode', 'angkatan__tahun_masuk', 'mata_kuliah__kode'],
            },
        ),
        migrations.AddConstraint(
            model_name='pembelajaran',
            constraint=models.UniqueConstraint(fields=('prodi', 'angkatan', 'mata_kuliah', 'dosen'), name='uniq_template_pengajaran'),
        ),
        migrations.AddConstraint(
            model_name='angkatan',
            constraint=models.UniqueConstraint(fields=('prodi', 'tahun_masuk', 'nama'), name='uniq_angkatan_per_prodi'),
        ),
    ]
