# Generated by Django 3.2.7 on 2026-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruang',
            name='tipe',
            field=models.CharField(choices=[('KELAS', 'Kelas'), ('LAB', 'Laboratorium')], default='KELAS', max_length=20),
        ),
    ]
