# Generated by Django 3.2.7 on 2026-03-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0002_alter_ruang_tipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AturanJadwal',
        ),
    ]
