# Generated by Django 3.2.7 on 2026-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0003_delete_aturanjadwal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='angkatan',
            name='uniq_angkatan_per_prodi',
        ),
        migrations.RemoveField(
            model_name='angkatan',
            name='nama',
        ),
        migrations.AddField(
            model_name='angkatan',
            name='paket',
            field=models.CharField(choices=[('RGL', 'Reguler'), ('COOP', 'COOP')], default='RGL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='angkatan',
            constraint=models.UniqueConstraint(fields=('prodi', 'tahun_masuk', 'paket'), name='uniq_angkatan_per_prodi'),
        ),
    ]
