# Generated by Django 3.2.7 on 2026-03-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0004_auto_20260305_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_ke', models.PositiveSmallIntegerField(default=1)),
                ('hari', models.CharField(choices=[('SENIN', 'Senin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KAMIS', 'Kamis'), ('JUMAT', 'Jumat')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['semester', 'hari', 'jam_mulai', 'ruang__kode'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=20)),
                ('tipe', models.CharField(choices=[('GANJIL', 'Ganjil'), ('GENAP', 'Genap'), ('PENDEK', 'Pendek')], max_length=10)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-tahun_akademik', 'tipe'],
            },
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('tahun_akademik', 'tipe'), name='uniq_tahun_tipe_semester'),
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='pembelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_set', to='penjadwalan.pembelajaran'),
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.ruang'),
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_set', to='penjadwalan.semester'),
        ),
        migrations.AddConstraint(
            model_name='jadwalkuliah',
            constraint=models.UniqueConstraint(fields=('semester', 'hari', 'jam_mulai', 'ruang'), name='uniq_jadwal_ruang_slot'),
        ),
        migrations.AddConstraint(
            model_name='jadwalkuliah',
            constraint=models.UniqueConstraint(fields=('semester', 'hari', 'jam_mulai', 'pembelajaran', 'kelas_ke'), name='uniq_jadwal_kelas_slot'),
        ),
    ]
