# Generated by Django 3.2.7 on 2026-03-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0005_auto_20260306_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelajaran',
            name='detail_ruangan',
            field=models.CharField(choices=[('KELAS', 'Kelas'), ('LAB', 'Laboratorium')], default='KELAS', max_length=20),
        ),
    ]
