# Generated by Django 3.2.7 on 2026-05-08 09:13

from django.db import migrations, models
import django.utils.timezone


def ensure_ruangan_table(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "penjadwalan_ruangan"

    if table_name in connection.introspection.table_names():
        return

    schema_editor.execute(
        """
        CREATE TABLE penjadwalan_ruangan (
            id integer PRIMARY KEY AUTOINCREMENT,
            kode varchar(50) NOT NULL UNIQUE,
            nama varchar(150) NOT NULL,
            tipe varchar(20) NOT NULL,
            kapasitas integer unsigned NOT NULL,
            board_type varchar(20) NULL,
            prodi varchar(150) NULL,
            aktif bool NOT NULL DEFAULT 1,
            catatan text NULL,
            created_at datetime NOT NULL,
            updated_at datetime NOT NULL
        )
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("penjadwalan", "0007_rebuild_penjadwalan_for_batch_storage"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Ruangan",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("kode", models.CharField(max_length=50, unique=True)),
                        ("nama", models.CharField(max_length=150)),
                        ("tipe", models.CharField(choices=[("KELAS", "Kelas"), ("LAB", "Laboratorium")], default="KELAS", max_length=20)),
                        ("kapasitas", models.PositiveIntegerField(default=0)),
                        ("board_type", models.CharField(blank=True, choices=[("PAPAN_TULIS", "Papan Tulis"), ("SMARTBOARD", "Smartboard")], max_length=20, null=True)),
                        ("prodi", models.CharField(blank=True, max_length=150, null=True)),
                        ("aktif", models.BooleanField(default=True)),
                        ("catatan", models.TextField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "ordering": ["tipe", "nama"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(ensure_ruangan_table, migrations.RunPython.noop),
            ],
        ),
    ]
