# Generated by Django 3.2.7 on 2023-07-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoinPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('item_number', models.CharField(blank=True, max_length=20, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('element', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_grade_1', models.TextField(blank=True, null=True)),
                ('description_grade_2', models.TextField(blank=True, null=True)),
                ('description_grade_3', models.TextField(blank=True, null=True)),
                ('description_grade_4', models.TextField(blank=True, null=True)),
                ('kriteriaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akreditasi.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('file', 'file'), ('folder', 'folder')], default='file', max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='akreditasi/files/')),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dosen')),
                ('kriteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akreditasi.kriteria')),
                ('matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akreditasi.poinpenilaian')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akreditasi.filefolder')),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programstudi')),
            ],
        ),
    ]
