# Generated by Django 3.2.7 on 2022-02-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('file', 'file'), ('folder', 'folder')], default='file', max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='akreditasi/files/')),
            ],
        ),
        migrations.CreateModel(
            name='FileFolder2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('file', 'file'), ('folder', 'folder')], default='file', max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='akreditasi/files/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.filefolder1')),
            ],
        ),
        migrations.CreateModel(
            name='FileFolder3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('file', 'file'), ('folder', 'folder')], default='file', max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='akreditasi/files/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.filefolder2')),
            ],
        ),
        migrations.CreateModel(
            name='PoinPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=100)),
                ('indikator', models.TextField()),
                ('skor_maksimal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileFolder4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('file', 'file'), ('folder', 'folder')], default='file', max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='akreditasi/files/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.filefolder3')),
            ],
        ),
        migrations.AddField(
            model_name='filefolder1',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.poinpenilaian'),
        ),
    ]
