# Generated by Django 3.2.7 on 2022-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poinpenilaian',
            name='indikator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poinpenilaian',
            name='skor_maksimal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
