# Generated by Django 3.2.7 on 2022-02-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0002_auto_20220226_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefolder1',
            name='parent',
        ),
        migrations.AddField(
            model_name='filefolder1',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akreditasi.poinpenilaian'),
        ),
        migrations.AddField(
            model_name='filefolder1',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akreditasi.filefolder1'),
        ),
    ]
