# Generated by Django 3.2.7 on 2022-02-26 14:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('akreditasi', '0003_auto_20220226_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileFolder1',
            new_name='FileFolder',
        ),
        migrations.RemoveField(
            model_name='filefolder3',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='filefolder4',
            name='parent',
        ),
        migrations.DeleteModel(
            name='FileFolder2',
        ),
        migrations.DeleteModel(
            name='FileFolder3',
        ),
        migrations.DeleteModel(
            name='FileFolder4',
        ),
    ]
