# Generated by Django 3.2.7 on 2022-03-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('akreditasi', '0005_auto_20220315_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dosen'),
        ),
    ]
