# Generated by Django 3.2 on 2023-06-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('akreditasi', '0005_auto_20220315_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poinpenilaian',
            old_name='indikator',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='poinpenilaian',
            old_name='skor_maksimal',
            new_name='description_grade_1',
        ),
        migrations.RemoveField(
            model_name='poinpenilaian',
            name='kode',
        ),
        migrations.AddField(
            model_name='filefolder',
            name='dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dosen'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programstudi'),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='description_grade_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='description_grade_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='description_grade_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='item_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='kriteriaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akreditasi.kriteria'),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poinpenilaian',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poinpenilaian',
            name='element',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
