# Generated by Django 3.2.7 on 2022-03-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('akreditasi', '0006_filefolder_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programstudi'),
        ),
    ]
