import {
  get, post, deleteRequest, patch,
} from './base/index';
import {
  POINPENILAIAN,
  FOLDERBYMATRIX,
  FOLDERBYFOLDER,
  FOLDER,
  PENUGASANPENGAJARAN,
  EVALUASIPERKULIAHAN,
  PORTOFOLIOPERKULIAHAN,
  SURATPENUGASAN,
  MATAKULIAH,
  KURIKULUM,
  PROGRAMSTUDI,
  DOSEN,
  FOLDERBYKRITERIA,
} from './urls';

export default {
  // GET
  getMatrixPenilaian: () => get(POINPENILAIAN),
  getMataKuliah: () => get(MATAKULIAH),
  getEvaluasiPerkuliahan: () => get(EVALUASIPERKULIAHAN),
  getSuratPenugasan: () => get(SURATPENUGASAN),
  getPenugasanPengajaran: () => get(PENUGASANPENGAJARAN),
  getPortofolioPerkuliahan: () => get(PORTOFOLIOPERKULIAHAN),
  getKurikulum: () => get(KURIKULUM),
  getProgramStudi: () => get(PROGRAMSTUDI),
  getDosen: () => get(DOSEN),
  getDosenbyId: (id) => get(`${DOSEN}${id}/`),
  getProgramStudibyId: (id) => get(`${PROGRAMSTUDI}${id}/`),
  getKurikulumbyId: (id) => get(`${KURIKULUM}${id}/`),
  getMataKuliahbyId: (id) => get(`${MATAKULIAH}${id}/`),
  getEvaluasiPerkuliahanbyId: (id) => get(`${EVALUASIPERKULIAHAN}${id}/`),
  getPenugasanPengajaranbyId: (id) => get(`${PENUGASANPENGAJARAN}${id}/`),
  getPortofolioPerkuliahanbyId: (id) => get(`${PORTOFOLIOPERKULIAHAN}${id}/`),
  getFolderbyMatrix: (id) => get(`${FOLDERBYMATRIX}${id}`),
  getFolderbyFolder: (id) => get(`${FOLDERBYFOLDER}${id}`),
  getFolderbyKriteria: (id) => get(`${FOLDERBYKRITERIA}${id}`),
  // POST
  postMatrixPenilaian: (body, params) => post(POINPENILAIAN, body, params),
  postMataKuliah: (body, params) => post(MATAKULIAH, body, params),
  postSuratPenugasan: (body, params) => post(SURATPENUGASAN, body, params),
  postPenugasanPengajaran: (body, params) => post(PENUGASANPENGAJARAN, body, params),
  postKurikulum: (body, params) => post(KURIKULUM, body, params),
  postDosen: (body, params) => post(DOSEN, body, params),
  postProgramStudi: (body, params) => post(PROGRAMSTUDI, body, params),
  postPortofolioPerkuliahan: (body, params) => post(PORTOFOLIOPERKULIAHAN, body, params),
  postEvaluasiPerkuliahan: (body, params) => post(EVALUASIPERKULIAHAN, body, params),
  // EDIT
  editMatrixPenilaian: (id, body, params) => patch(`${POINPENILAIAN}${id}/`, body, params),
  editMataKuliah: (id, body, params) => patch(`${MATAKULIAH}${id}/`, body, params),
  editSuratPenugasan: (id, body, params) => patch(`${SURATPENUGASAN}${id}/`, body, params),
  editPenugasanPengajaran: (id, body, params) => patch(`${PENUGASANPENGAJARAN}${id}/`, body, params),
  editKurikulum: (id, body, params) => patch(`${KURIKULUM}${id}/`, body, params),
  editProgramStudi: (id, body, params) => patch(`${PROGRAMSTUDI}${id}/`, body, params),
  editEvaluasiPerkuliahan: (id, body, params) => patch(`${EVALUASIPERKULIAHAN}${id}/`, body, params),
  editPortofolioPerkuliahan: (id, body, params) => patch(`${PORTOFOLIOPERKULIAHAN}${id}/`, body, params),
  // DELETE
  deleteMatrixPenilaian: (id) => deleteRequest(`${POINPENILAIAN}${id}/`),
  deleteMataKuliah: (id) => deleteRequest(`${MATAKULIAH}${id}/`),
  deleteSuratPenugasan: (id) => deleteRequest(`${SURATPENUGASAN}${id}/`),
  deletePenugasanPengajaran: (id) => deleteRequest(`${PENUGASANPENGAJARAN}${id}/`),
  deleteKurikulum: (id) => deleteRequest(`${KURIKULUM}${id}/`),
  deleteProgramStudi: (id) => deleteRequest(`${PROGRAMSTUDI}${id}/`),
  deleteDosen: (id) => deleteRequest(`${DOSEN}${id}/`),
  deleteEvaluasiPerkuliahan: (id) => deleteRequest(`${EVALUASIPERKULIAHAN}${id}/`),
  deletePortofolioPerkuliahan: (id) => deleteRequest(`${PORTOFOLIOPERKULIAHAN}${id}/`),
  // CRUD for FileFolder
  getCurrentFileFolder: (id) => get(`${FOLDER}${id}/`),
  postFolderFile: (body, params) => post(FOLDER, body, params),
  deleteFileFolder: (id) => deleteRequest(`${FOLDER}${id}/`),
  editFolderFile: (id, body, params) => patch(`${FOLDER}${id}/`, body, params),
};
